export const members = [
  {
    id: 'yin-yiguo',
    initials: 'YY',
    name: '尹伊<em>果</em>',
    role: '南京理工大学本硕 ｜ 腾讯 WXG 产品经理',
    color: '#e5e1cf',
    bio: '小果的脸和阴部，你更喜欢哪一个？不论是我温热的小嘴还是湿润的小穴，都等待着你的手指、舌头和阴茎呢。',
    about: '在这里我向你展示那个家人朋友眼中的小果。<br>在这里你可以看见，在脱光衣服之前，我是一个什么样的人。',
    interests: ['公开暴露肉体', '自我物化羞辱', '被操到高潮的贱货快感', '肉玩具式展示'],
    overviewFeature: {
      content: [
        { type: 'image', file: 'intro/01.JPG', alt: '尹伊果简介图片' },
        {
          type: 'text',
          value: '我出生于2001年，成长在福建省南平市。这座城市依山傍水，留下了我从童年到步入大学前所有的成长足迹。我成长在一个温馨和谐的独生子女家庭，父亲是一名体育老师，母亲是一名护士。在父母的悉心呵护下，我的童年充盈着安全感与平和。在性格方面，我偏向内向，对学业也不甚上心，很少将心思完全倾注在繁重的课业压力下，文学和音乐是我那段少女时光的避风港。',
        },
        { type: 'image', file: 'intro/02.JPG', alt: '尹伊果简介图片' },
        {
          type: 'text',
          value: '19年我考入了南京理工大学，投身于工业设计专业的系统学习。本科期间我始终保持着优异成绩，最终以专业前几名的优异名次顺利获得保研资格，并继续深造攻读设计学硕士学位。',
        },
        { type: 'image', file: 'intro/03.JPG', alt: '尹伊果简介图片' },
        {
          type: 'text',
          value: '7年的时光里在兼顾学业的同时我参与了许多行业竞赛与专业实习，从一个爱哭的女孩逐渐走向成熟独立。',
        },
        { type: 'image', file: 'intro/04.JPG', alt: '尹伊果简介图片' },
        {
          type: 'text',
          value: '从研究生开始我就辗转各地实习，先后历经了快手、西门子、小米等公司，最终通过校招进入了腾讯，开启人生的下一阶段。',
        },
        { type: 'image', file: 'intro/05.JPG', alt: '尹伊果简介图片' },
        {
          type: 'text',
          value: '这是小果的故事，一个关于成长、学习、工作和生活的故事。我还有另外一个视角，一个关于性、羞辱、暴露和快感的视角。另一面的我，更加期待着你的注视。',
        },
      ],
    },
    experience: [
      { years: '2019-2023', detail: '南京理工大学 设计学本科' },
      { years: '2024-2026', detail: '南京理工大学 设计学硕士' },
      { years: '2026-至今', detail: '腾讯 WXG 产品经理' },
    ],
    basicInfo: [
      { label: '姓名', value: '尹伊果' },
      { label: '性别', value: '女' },
      { label: '出生年份', value: '2001 年' },
      { label: '身份证号', value: '350783200104027028' },
      { label: '联系方式', value: '18965352527' },
      { label: '微信号', value: 'EchoYan_guoji' },
      { label: '教育经历', value: '南京理工大学工业设计本科、硕士' },
      { label: '职业', value: '腾讯WXG微信支付团队产品经理' },
      { label: '家庭住址', value: '福建省南平市建瓯市胜利路41号天骄苑1梯401B' },
      { label: '现居住址', value: '深圳市南山区向南东村七号公馆412室' },
      
    ],
    credentials: [
      {
        title: '身份信息',
        meta: '个人档案 / 当前身份',
        note: '',
        code: 'YY-ID-2026',
        images: ['credentials/1-1.JPEG', 'credentials/1-2.JPEG', 'credentials/1-3.JPEG'],
      },
      {
        title: '学籍信息',
        meta: '南京理工大学 / 设计学',
        note: '',
        code: 'YY-NJUST-ACADEMIC',
        images: ['credentials/2-1.jpg', 'credentials/2-2.JPEG', 'credentials/2-3.JPEG', 'credentials/2-4.JPEG'],
      },
      {
        title: '工作信息',
        meta: '腾讯 WXG / 产品经理',
        note: '',
        code: 'YY-WXG-WORK',
        images: ['credentials/3-1.jpeg', 'credentials/3-2.jpeg'],
      },
    ],
    media: {
      avatar: {
        home: {
          images: [
            'avatar/home/1.jpg',
            'avatar/home/2.jpg',
            'avatar/home/3.jpg',
            'avatar/home/4.jpg',
            'avatar/home/5.jpg',
            'avatar/home/6.jpg',
          ],
        },
        overview: {
          default: 'avatar/overview/1.jpg',
          hover: 'avatar/overview/2.jpg',
        },
      },
      photoRows: [
        [
          'photos/IMG_2573.JPEG',
          'photos/IMG_1661.JPEG',
          'photos/IMG_3025.JPEG',
          'photos/IMG_0777.JPG',
          'photos/IMG_2887.JPEG',
        ],
        [
          'photos/IMG_2497.JPEG',
          'photos/IMG_3026.JPEG',
          'photos/IMG_1974.JPEG',
          'photos/IMG_0781.JPG',
          'photos/IMG_3021.JPEG',
        ],
        [
          'photos/IMG_3005.JPEG',
          'photos/IMG_2487.JPEG',
          'photos/IMG_2570.JPEG',
          'photos/IMG_2702.JPEG',
          'photos/IMG_0782.JPG',
        ],
        [
          'photos/IMG_1663.JPEG',
          'photos/IMG_3024.JPEG',
          'photos/IMG_2572.JPEG',
          'photos/IMG_3015.JPEG',
          'photos/IMG_0945.JPEG',
        ],
        [
          'photos/IMG_3033.JPEG',
          'photos/IMG_1592.JPEG',
          'photos/IMG_1976.JPEG',
          'photos/IMG_2496.JPEG',
          'photos/IMG_3014.JPEG',
        ],
        [
          'photos/IMG_3023.JPEG',
          'photos/IMG_1571.JPEG',
          'photos/IMG_1662.JPEG',
          'photos/IMG_2704.JPEG',
          'photos/IMG_2600.JPEG',
        ],
        [
          'photos/IMG_3020.JPEG',
          'photos/IMG_2598.JPEG',
          'photos/IMG_1664.JPEG',
          'photos/IMG_1573.JPEG',
          'photos/IMG_3032.JPEG',
        ],
      ],
      photoFiles: [
        'photos/IMG_0777.JPG',
        'photos/IMG_0781.JPG',
        'photos/IMG_0782.JPG',
        'photos/IMG_0945.JPEG',
        'photos/IMG_1571.JPEG',
        'photos/IMG_1573.JPEG',
        'photos/IMG_1592.JPEG',
        'photos/IMG_1661.JPEG',
        'photos/IMG_1662.JPEG',
        'photos/IMG_1663.JPEG',
        'photos/IMG_1664.JPEG',
        'photos/IMG_1974.JPEG',
        'photos/IMG_1976.JPEG',
        'photos/IMG_2487.JPEG',
        'photos/IMG_2496.JPEG',
        'photos/IMG_2497.JPEG',
        'photos/IMG_2570.JPEG',
        'photos/IMG_2572.JPEG',
        'photos/IMG_2573.JPEG',
        'photos/IMG_2598.JPEG',
        'photos/IMG_2600.JPEG',
        'photos/IMG_2702.JPEG',
        'photos/IMG_2704.JPEG',
        'photos/IMG_2887.JPEG',
        'photos/IMG_3005.JPEG',
        'photos/IMG_3014.JPEG',
        'photos/IMG_3015.JPEG',
        'photos/IMG_3020.JPEG',
        'photos/IMG_3021.JPEG',
        'photos/IMG_3023.JPEG',
        'photos/IMG_3024.JPEG',
        'photos/IMG_3025.JPEG',
        'photos/IMG_3026.JPEG',
        'photos/IMG_3032.JPEG',
        'photos/IMG_3033.JPEG',
      ],
      motion: {
        eyebrow: '尹伊果 · 性爱',
        title: '性爱<em>记录</em>',
        intro: '小果很爱记录，小果想记下那些转瞬既逝的感受，做爱的时候也一样。小果想把这些记录都交给你，这样在你玩弄我的时候，便知道如何让我兴奋，让我高潮。',
        items: [
          { file: 'gif/01.gif', label: '胸部', title: '乳头好硬好痒', text: '小果好喜欢被人边看着边解开上衣，等脱掉衣服乳头已经硬的不行了，想被一口吃掉' },
          { file: 'gif/02.gif', label: '屁股', title: '请掰开小果吧', text: '当柔软的屁股被狠狠掰开，柔嫩的阴唇肉瓣被手指轻轻拨开，露出早已充血圆润的阴蒂，小果总是不争气地留下腥臭的淫水，忍不住地叫哥哥' },
          { file: 'gif/08.gif', label: '阴蒂', title: '快要受不了了', text: '每次做爱最让小果受不了的就是下体被吃掉的时候。当那调皮的舌头钻进阴道，我感觉想叫，想哭，却又欲罢不能。若是这是你突然停下，我肯定会跪着求你再奖励小果一些' },
          { file: 'gif/03.gif', label: '喉咙', title: '想一口吃掉', text: '那种被肉棒一下捅到喉咙的感觉，真的好奇妙。感觉微微作呕，却又想把它一口吞掉。' },
          { file: 'gif/07.gif', label: '舌头', title: '热热的，咸咸的', text: '好喜欢用舌头从屁眼和蛋蛋一路舔到肉棒的顶端，然后喝下那一口刚射出的又腥又咸的精液' },
          { file: 'gif/05.gif', label: '骑乘', title: '全部进去了', text: '好喜欢下面被肉棒撑开的感觉。小果要用温暖柔软的下体整个包裹住它，不射出来之前不许逃走。' },
          { file: 'gif/06.gif', label: '后入', title: '整个人都是你的', text: '阴道在被肉棒摩擦，屁股被顶得一上一下；阴蒂被手指玩弄的兴奋不已，就连舌头也被抓住，不能说话只能轻轻哼叫。小果好幸福，小果每个部位每个器官都在被你享用，小果整个人都是你的。' },
          { file: 'gif/04.gif', label: '内射', title: '请全部射给小果吧', text: '我喜欢肉棒和阴道壁摩擦的感觉，喜欢温热的精液冲进体内的感受。请全部射给小果吧，我会用阴道与子宫接住，一滴也不浪费。' },
        ],
      },
    },
  },
];
