export const members = [
  {
    id: 'yin-yiguo',
    initials: 'YY',
    name: '尹伊<em>果</em>',
    role: '南京理工大学本硕 ｜ 腾讯 WXG 产品经理',
    color: '#e5e1cf',
    bio: '我的脸和阴部，你更喜欢哪一个？不论是我温热的小嘴还是湿润的小穴，都等待着你的手指、舌头和阴茎呢。',
    about: '我在南京理工大学完成了设计学本科与硕士学习，之后进入腾讯 WXG 担任产品经理。我最喜欢的事情就是想象自己成为一个人人都可以肆意使用的公共玩具，那种与自己乖巧表象背离的感觉让我欲罢不能。我柔软细嫩的胸部和温热湿润的小穴无时无刻不在渴望被当众玩弄。偶尔给身边的男同事看看我内裤里的景象已经不能满足我。请尽情地注视我、欣赏我吧，对着我的脸、嘴、乳头、阴蒂和肛门。我想在你们的注视和玩弄中喷出水花。',
    interests: ['公开暴露肉体', '自我物化羞辱', '被操到高潮的贱货快感', '肉玩具式展示'],
    experience: [
      { years: '2019-2023', detail: '南京理工大学 设计学本科' },
      { years: '2024-2026', detail: '南京理工大学 设计学硕士' },
      { years: '2026-至今', detail: '腾讯 WXG 产品经理' },
    ],
    credentials: [
      {
        title: '身份信息',
        meta: '个人档案 / 当前身份',
        note: '我2001年出生在福建省南平市，大学之前的生活与学习经历都在那里度过。父亲是一个体育老师，母亲是一名护士，我是家中独女，从小在父母的关爱下成长。',
        code: 'YY-ID-2026',
        images: ['credentials/1-1.JPEG', 'credentials/1-2.JPEG', 'credentials/1-3.JPEG'],
      },
      {
        title: '学籍信息',
        meta: '南京理工大学 / 设计学',
        note: '后来我考入南京理工大学设计学专业，本科以专业前几名的成绩拿到了保研资格，之后继续在南京理工大学攻读设计学硕士学位。',
        code: 'YY-NJUST-ACADEMIC',
        images: ['credentials/2-1.jpg', 'credentials/2-2.JPEG', 'credentials/2-3.JPEG', 'credentials/2-4.JPEG'],
      },
      {
        title: '工作信息',
        meta: '腾讯 WXG / 产品经理',
        note: '毕业后我在腾讯 WXG 的微信支付团队担任产品经理，负责设计和优化支付相关的用户体验和界面设计。',
        code: 'YY-WXG-WORK',
        images: ['credentials/3-1.jpeg', 'credentials/3-2.jpeg'],
      },
      {
        title: '社交媒体',
        meta: '公开平台 / 个人渠道',
        note: '如果你想了解更多关于我的信息，可以通过我的社交媒体渠道关注我，我会在这些平台上分享我的生活点滴。当然，如果你想享受我的身体，也可以通过这些渠道找到我，或者拨打我的电话 18965352527。',
        code: 'YY-SOCIAL-2026',
        images: ['credentials/4-1.JPEG', 'credentials/4-2.JPEG'],
      },
    ],
    media: {
      avatar: {
        home: {
          default: 'avatar/home/1.jpg',
          hover: 'avatar/home/2.jpg',
        },
        overview: {
          default: 'avatar/overview/1.jpg',
          hover: 'avatar/overview/2.jpg',
        },
      },
      photoRows: [
        [
          'photos/IMG_2573.JPEG',
          'photos/IMG_1661.JPEG',
          'photos/IMG_3025.JPEG',
          'photos/IMG_0777.JPG',
          'photos/IMG_2887.JPEG',
        ],
        [
          'photos/IMG_2497.JPEG',
          'photos/IMG_3026.JPEG',
          'photos/IMG_1974.JPEG',
          'photos/IMG_0781.JPG',
          'photos/IMG_3021.JPEG',
        ],
        [
          'photos/IMG_3005.JPEG',
          'photos/IMG_2487.JPEG',
          'photos/IMG_2570.JPEG',
          'photos/IMG_2702.JPEG',
          'photos/IMG_0782.JPG',
        ],
        [
          'photos/IMG_1663.JPEG',
          'photos/IMG_3024.JPEG',
          'photos/IMG_2572.JPEG',
          'photos/IMG_3015.JPEG',
          'photos/IMG_0945.JPEG',
        ],
        [
          'photos/IMG_3033.JPEG',
          'photos/IMG_1592.JPEG',
          'photos/IMG_1976.JPEG',
          'photos/IMG_2496.JPEG',
          'photos/IMG_3014.JPEG',
        ],
        [
          'photos/IMG_3023.JPEG',
          'photos/IMG_1571.JPEG',
          'photos/IMG_1662.JPEG',
          'photos/IMG_2704.JPEG',
          'photos/IMG_2600.JPEG',
        ],
        [
          'photos/IMG_3020.JPEG',
          'photos/IMG_2598.JPEG',
          'photos/IMG_1664.JPEG',
          'photos/IMG_1573.JPEG',
          'photos/IMG_3032.JPEG',
        ],
      ],
      photoFiles: [
        'photos/IMG_0777.JPG',
        'photos/IMG_0781.JPG',
        'photos/IMG_0782.JPG',
        'photos/IMG_0945.JPEG',
        'photos/IMG_1571.JPEG',
        'photos/IMG_1573.JPEG',
        'photos/IMG_1592.JPEG',
        'photos/IMG_1661.JPEG',
        'photos/IMG_1662.JPEG',
        'photos/IMG_1663.JPEG',
        'photos/IMG_1664.JPEG',
        'photos/IMG_1974.JPEG',
        'photos/IMG_1976.JPEG',
        'photos/IMG_2487.JPEG',
        'photos/IMG_2496.JPEG',
        'photos/IMG_2497.JPEG',
        'photos/IMG_2570.JPEG',
        'photos/IMG_2572.JPEG',
        'photos/IMG_2573.JPEG',
        'photos/IMG_2598.JPEG',
        'photos/IMG_2600.JPEG',
        'photos/IMG_2702.JPEG',
        'photos/IMG_2704.JPEG',
        'photos/IMG_2887.JPEG',
        'photos/IMG_3005.JPEG',
        'photos/IMG_3014.JPEG',
        'photos/IMG_3015.JPEG',
        'photos/IMG_3020.JPEG',
        'photos/IMG_3021.JPEG',
        'photos/IMG_3023.JPEG',
        'photos/IMG_3024.JPEG',
        'photos/IMG_3025.JPEG',
        'photos/IMG_3026.JPEG',
        'photos/IMG_3032.JPEG',
        'photos/IMG_3033.JPEG',
      ],
    },
  },
];